name: phosphorylation-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9.7
  - pip=22.1.2
  # Core scientific python
  - numpy=1.20.3
  - pandas=1.3.4
  - scikit-learn=1.0.2
  - keras=2.8.0
  - tensorflow=2.8.0

